apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-frontend
  labels:
    app: movie-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-frontend
  template:
    metadata:
      labels:
        app: movie-frontend
    spec:
      containers:
      - name: movie-frontend
        image: msyhu/movie-frontend:0.0.1
        ports:
        - containerPort: 5000
